- name: exec docker-compose
  hosts: my-ec2-instances
  become: true

  tasks:
    - name: ubicar ruta 
      command: sudo cd /home/ec2-user

    - name: Activar daemon 
      command: sudo systemctl start docker  

    - name: Ejecutar docker compose
      command: sudo docker-compose up -d

    
